name: Generate Snake Contribution

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily at midnight UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate GitHub Contribution Snake

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate the snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ishpreet404
          outputs: |
            assets/github-contribution-grid-snake.svg
            assets/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit and Push SVG
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add assets/*.svg
          git commit -m "🐍 Update contribution snake SVG" || echo "No changes"
          git push
